var questions = [
    { letter: "a",status: 0, actualPositionGame: 0,
      answer:  { 0 :"abducir",1 :"alegre",2 :"ahorrar"},  
      question:{ 0 : ("CON LA A. Dicho de una supuesta criatura extraterrestre: Apoderarse de alguien"),
                 1 : ("CON LA A. Sinónimo de contento."),
                 2 : ("CON LA A. Guardar dinero como previsión para necesidades futuras")} },
    { letter: "b",status: 0, actualPositionGame: 0,
      answer:  { 0 :"bingo",1 :"biblioteca",2 :"beca"},  
      question:{ 0 : ("CON LA B. Juego que ha sacado de quicio a todos los 'Skylabers' en las sesiones de precurso"),
                 1 : ("CON LA B. Lugar en el que se lleva a cabo el préstamo de libros"),
                 2 : ("CON LA B. Subvención para realizar estudios o investigaciones ")} },
    { letter: "c",status: 0, actualPositionGame: 0,
      answer:  { 0 :"churumbel",1 :"cereza",2 :"culpar"},  
      question:{ 0 : ("CON LA C. Niño, crío, bebé"),
                 1 : ("CON LA C. Fruto del cerezo de color rojo oscuro"),
                 2 : ("CON LA C. Atribuir o echar la culpa a alguien")} },
    { letter: "d",status: 0, actualPositionGame: 0,
      answer:  { 0 :"diarrea",1 :"descargar",2 :"deportar"},  
      question:{ 0 : ("CON LA D. Anormalidad en la función del aparato digestivo caracterizada por frecuentes evacuaciones y su consistencia líquida") ,
                 1 : ("CON LA D. Si le añado el prefijo des- al verbo cargar, tienes…"),
                 2 : ("CON LA D. Desterrar a alguien de algún lugar, por lo regular extranjero, y confinarlo allí por razones políticas o como castigo")} },
    { letter: "e",status: 0, actualPositionGame: 0,
      answer:  { 0 :"ectoplasma",1 :"enero",2 :"envoltorio"},  
      question:{ 0 : ("CON LA E. Gelatinoso y se encuentra debajo de la membrana plasmática. Los cazafantasmas medían su radiación"),
                 1 : ("CON LA E. Primer mes del año."),
                 2 : ("CON LA E. Capa exterior que cubre natural o artificialmente una cosa")} },
    { letter: "f",status: 0, actualPositionGame: 0,
      answer:  { 0 :"facil",1 :"frutero",2 :"frenar"},  
      question:{ 0 : ("CON LA F. Que no requiere gran esfuerzo, capacidad o dificultad"), 
                 1 : ("CON LA F. Recipiente en el que se coloca la fruta. "),
                 2 : ("CON LA F. Moderar o parar el movimiento de algo")} },
    { letter: "g",status: 0, actualPositionGame: 0,
      answer:  { 0 :"galaxia",1 :"guitarra",2 :"grupo"},  
      question:{ 0 : ("CON LA G. Conjunto enorme de estrellas, polvo interestelar, gases y partículas"), 
                 1 : ("CON LA G. Instrumento musical con seis cuerdas que hacemos sonar con los dedos"),
                 2 : ("CON LA G. Pluralidad de seres o cosas que forman un conjunto")} },
    { letter: "h",status: 0, actualPositionGame: 0,
      answer:  { 0 :"harakiri",1 :"hermano",2 :"huelga"},  
      question:{ 0 : ("CON LA H. Suicidio ritual japonés por desentrañamiento"), 
                 1 : ("CON LA H. ¿Cómo se llama la persona que tiene el mismo padre y la misma madre que tú?"),
                 2 : ("CON LA H. Interrupción colectiva de la actividad laboral por parte de los trabajadores con el fin de reivindicar ciertas condiciones o manifestar una protesta ")} },
    { letter: "i",status: 0, actualPositionGame: 0,
      answer:  { 0 :"iglesia",1 :"invisible",2 :"indignar"},  
      question:{ 0 : ("CON LA I. Templo cristiano"), 
                 1 : ("CON LA I. Añade un prefijo a la palabra visible para obtener lo contrario y tendrás…"),
                 2 : ("CON LA I. Irritar, enfadar vehementemente a alguien ")} },
    { letter: "j",status: 0, actualPositionGame: 0,
      answer:  { 0 :"jabali",1 :"jarabe",2 :"jubilado"},  
      question:{ 0 : ("CON LA J. Variedad salvaje del cerdo que sale en la película 'El Rey León', de nombre Pumba"), 
                 1 : ("CON LA J. Medicamento que se presenta en forma de líquido espeso, generalmente dulce y pegajoso, con fines curativos"),
                 2 : ("CON LA J. Persona que ha dejado de trabajar y percibe una pensión")} },
    { letter: "k",status: 0, actualPositionGame: 0,
      answer:  { 0 :"kamikaze",1 :"koala",2 :"kaki"},  
      question:{ 0 : ("CON LA K. Persona que se juega la vida realizando una acción temeraria"),
                 1 : ("CON LA K. Mamífero marsupial arborícola parecido a un oso pequeño, propio de los eucaliptales australianos ."),
                 2 : ("CON LA K. Color utilizado en bienes militares")} },
    { letter: "l",status: 0, actualPositionGame: 0,
      answer:  { 0 :"licantropo",1 :"libreria",2 :"liberar"},  
      question:{ 0 : ("CON LA L. Hombre lobo"), 
                 1 : ("CON LA L. Lugar en el que se compran libros"),
                 2 : ("CON LA L. Hacer que alguien o algo quede libre, eximir a alguien de una obligación")} },
    { letter: "m",status: 0, actualPositionGame: 0,
      answer:  { 0 :"misantropo",1 :"comba",2 :"manifestacion"},  
      question:{ 0 : ("CON LA M. Persona que huye del trato con otras personas o siente gran aversión hacia ellas"), 
                 1 : ("CONTIENE LA M. Juego que consiste en saltar por encima de una cuerda que se hace pasar por debajo de los pies y sobre la cabeza de quien salta"),
                 2 : ("CON LA M. Reunión pública, generalmente al aire libre, en la que los asistentes reclaman algo o expresan su protesta por algo")} },
    { letter: "n",status: 0, actualPositionGame: 0,
      answer:  { 0 :"necedad",1 :"naranja",2 :"nacionalidad"},  
      question:{ 0 : ("CON LA N. Demostración de poca inteligencia"), 
                 1 : ("CON LA N. Del campo semántico de los colores y el color de una fruta con la que podemos hacer zumo"),
                 2 : ("CON LA N. Estado propio de la persona nacida o naturalizada en una nación ")} },
    { letter: "ñ",status: 0, actualPositionGame: 0,
      answer:  { 0 :"señal",1 :"niño",2 :"soñar"},  
      question:{ 0 : ("CONTIENE LA Ñ. Indicio que permite deducir algo de lo que no se tiene un conocimiento directo."), 
                 1 : ("CONTIENE LA Ñ. Persona que tiene pocos años"),
                 2 : ("CONTIENE LA Ñ. Representarse en la fantasía imágenes o sucesos mientras se duerme ")} },
    { letter: "o",status: 0, actualPositionGame: 0,
      answer:  { 0 :"orco",1 :"oscuro",2 :"organizacion"},  
      question:{ 0 : ("CON LA O. Humanoide fantástico de apariencia terrible y bestial, piel de color verde creada por el escritor Tolkien"), 
                 1 : ("CON LA O. Antónimo de claro..."),
                 2 : ("CON LA O. Asociación de personas regulada por un conjunto de normas en función de determinados fines")} },
    { letter: "p",status: 0, actualPositionGame: 0,
      answer:  { 0 :"protoss",1 :"panadero",2 :"promover"},  
      question:{ 0 : ("CON LA P. Raza ancestral tecnológicamente avanzada que se caracteriza por sus grandes poderes psíonicos del videojuego StarCraft"), 
                 1 : ("CON LA P. Persona que vende en una panadería"),
                 2 : ("CON LA P. Iniciar o impulsar una idea o proyecto procurando su logro")} },
    { letter: "q",status: 0, actualPositionGame: 0,
      answer:  { 0 :"queso",1 :"quiosco",2 :"delinquir"},  
      question:{ 0 : ("CON LA Q. Producto obtenido por la maduración de la cuajada de la leche"), 
                 1 : ("CON LA Q. Puesto de venta en la calle"),
                 2 : ("CONTIENE LA Q. Cometer delito")} },
    { letter: "r",status: 0, actualPositionGame: 0,
      answer:  { 0 :"raton",1 :"rana",2 :"reciclar"},  
      question:{ 0 : ("CON LA R. Roedor"), 
                 1 : ("CON LA R. Anfibio de cuatro patas, con presención en selvas y riberas."),
                 2 : ("CON LA R. Someter material usado a un proceso para que se pueda volver a utilizar")} },
    { letter: "s",status: 0, actualPositionGame: 0,
      answer:  { 0 :"stackoverflow",1 :"sosa",2 :"suprimir"},  
      question:{ 0 : ("CON LA S. Comunidad salvadora de todo desarrollador informático"), 
                 1 : ("CON LA S. Comida contraria a tener mucha sal"),
                 2 : ("CON LA S. Hacer cesar, hacer desaparecer, anular")} },
    { letter: "t",status: 0, actualPositionGame: 0,
      answer:  { 0 :"terminator",1 :"tarta",2 :"tasa"},  
      question:{ 0 : ("CON LA T. Película del director James Cameron que consolidó a Arnold Schwarzenegger como actor en 1984"), 
                 1 : ("CON LA T. Pastel grande que no suele faltar en los cumpleaños"),
                 2 : ("CON LA T.  Tributo que se impone a la utilización de ciertos servicios, o al ejercicio de ciertas actividades")} },
    { letter: "u",status: 0, actualPositionGame: 0,
      answer:  { 0 :"unamuno",1 :"usar",2 :"urgencia"},  
      question:{ 0 : ("CON LA U. Escritor y filósofo español de la generación del 98 autor del libro 'Niebla' en 1914"), 
                 1 : ("CON LA U. Sinónimo de utilizar"),
                 2 : ("CON LA U. Necesidad o falta apremiante, inmediata obligación de hacer algo ")} },
    { letter: "v",status: 0, actualPositionGame: 0,
      answer:  { 0 :"vikingos",1 :"vaso",2 :"vivienda"},  
      question:{ 0 : ("CON LA V. Nombre dado a los miembros de los pueblos nórdicos originarios de Escandinavia, famosos por sus incursiones y pillajes en Europa"), 
                 1 : ("CON LA V. Recipiente que sirve para beber"),
                 2 : ("CON LA V. Lugar cerrado y cubierto construido para ser habitado por personas")} },
    { letter: "w",status: 0, actualPositionGame: 0,
      answer:  { 0 :"sandwich",1 :"waterpolo",2 :"whiski"},  
      question:{ 0 : ("CONTIENE LA W. Emparedado hecho con dos rebanadas de pan entre las cuales se coloca jamón y queso"), 
                 1 : ("CON LA W. Juego practicado en una pisicina entre dos equipos, y con dos porterías"),
                 2 : ("CON LA W. Licor alcóholico que se obtiene del destilado del grano de algunas plantas")} },
    { letter: "x",status: 0, actualPositionGame: 0,
      answer:  { 0 :"botox",1 :"xilofono",2 :"exaltar"},  
      question:{ 0 : ("CONTIENE LA X. Toxina bacteriana utilizada en cirujía estética"), 
                 1 : ("CON LA X. Intrumento musical formado por laminas de diferente tamaño que, suenan golpeadas."),
                 2 : ("CONTIENE LA X. Avivar o aumentar un sentimiento o pasión, realzar el mérito o las cualidades de alguien")} },
    { letter: "y",status: 0, actualPositionGame: 0,
      answer:  { 0 :"peyote",1 :"yegua",2 :"cayuco"},  
      question:{ 0 : ("CONTIENE LA Y. Pequeño cáctus conocido por sus alcaloides psicoactivos utilizado de forma ritual y medicinal por indígenas americanos"), 
                 1 : ("CON LA Y. Hembra del caballo"),
                 2 : ("CON LA Y. Embarcación india de una pieza, más pequeña que la canoa, con el fondo plano, que se gobierna con el canalete")} },
    { letter: "z",status: 0, actualPositionGame: 0,
      answer:  { 0 :"zen",1 :"zapato",2 :"zoologico"},  
      question:{ 0 : ("CON LA Z. Escuela de budismo que busca la experiencia de la sabiduría más allá del discurso racional"), 
                 1 : ("CON LA Z. Calzado que ponemos en los pies para caminar"),
                 2 : ("CON LA Z. Lugar en que se conservan, cuidan y crían diversas especies animales con fines didácticos o de entretenimiento")} },
]; 


/* CLONANDO OBJETOS JSON
var arrayPrimero = [2,1,4,{name:"pepe"}]

//JSON.parse(JSON.stringify(obj))

var arraySegundo =JSON.parse(JSON.stringify(arrayPrimero));

arrayPrimero[3].name = "juan";

console.log(arrayPrimero);
console.log(arraySegundo); */